#!/usr/bin/env sh
# generated from catkin/python/catkin/environment_cache.py

# based on a snapshot of the environment before and after calling the setup script
# it emulates the modifications of the setup script without recurring computations

# new environment variables

# modified environment variables
export CMAKE_PREFIX_PATH="/home/nico/Vision/SLAM/ORB_official/ORB_SLAM2/Examples/ROS/ORB_SLAM2/build-ORB_SLAM2-Desktop-Default/devel:$CMAKE_PREFIX_PATH"
export CPATH="/home/nico/Vision/SLAM/ORB_official/ORB_SLAM2/Examples/ROS/ORB_SLAM2/build-ORB_SLAM2-Desktop-Default/devel/include:$CPATH"
export LD_LIBRARY_PATH="/home/nico/Vision/SLAM/ORB_official/ORB_SLAM2/Examples/ROS/ORB_SLAM2/build-ORB_SLAM2-Desktop-Default/devel/lib:/home/nico/Vision/SLAM/ORB_official/ORB_SLAM2/Examples/ROS/ORB_SLAM2/build-ORB_SLAM2-Desktop-Default/devel/lib/x86_64-linux-gnu:/home/nico/catkin_ws/ugv/devel/lib/x86_64-linux-gnu:/home/nico/catkin_ws/test/devel/lib/x86_64-linux-gnu:/home/nico/catkin_ws/robot_localization/devel/lib/x86_64-linux-gnu:/home/nico/catkin_ws/tum_ardrone/devel/lib/x86_64-linux-gnu:/home/nico/catkin_ws/laser_camera_calibration/devel/lib/x86_64-linux-gnu:/opt/ros/indigo/lib/x86_64-linux-gnu:/home/nico/catkin_ws/ugv/devel/lib:/home/nico/catkin_ws/test/devel/lib:/home/nico/catkin_ws/robot_localization/devel/lib:/home/nico/catkin_ws/tum_ardrone/devel/lib:/home/nico/catkin_ws/laser_camera_calibration/devel/lib:/opt/ros/indigo/lib"
export PATH="/home/nico/Vision/SLAM/ORB_official/ORB_SLAM2/Examples/ROS/ORB_SLAM2/build-ORB_SLAM2-Desktop-Default/devel/bin:/home/nico/catkin_ws/ugv/devel/bin:/home/nico/catkin_ws/test/devel/bin:/home/nico/catkin_ws/robot_localization/devel/bin:/home/nico/catkin_ws/tum_ardrone/devel/bin:/home/nico/catkin_ws/laser_camera_calibration/devel/bin:/opt/ros/indigo/bin:/usr/lib/x86_64-linux-gnu/qt5/bin:/usr/bin:/usr/lib/x86_64-linux-gnu/qt5/bin:/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"
export PKG_CONFIG_PATH="/home/nico/Vision/SLAM/ORB_official/ORB_SLAM2/Examples/ROS/ORB_SLAM2/build-ORB_SLAM2-Desktop-Default/devel/lib/pkgconfig:/home/nico/Vision/SLAM/ORB_official/ORB_SLAM2/Examples/ROS/ORB_SLAM2/build-ORB_SLAM2-Desktop-Default/devel/lib/x86_64-linux-gnu/pkgconfig:/home/nico/catkin_ws/ugv/devel/lib/x86_64-linux-gnu/pkgconfig:/home/nico/catkin_ws/test/devel/lib/x86_64-linux-gnu/pkgconfig:/home/nico/catkin_ws/robot_localization/devel/lib/x86_64-linux-gnu/pkgconfig:/home/nico/catkin_ws/tum_ardrone/devel/lib/x86_64-linux-gnu/pkgconfig:/home/nico/catkin_ws/laser_camera_calibration/devel/lib/x86_64-linux-gnu/pkgconfig:/opt/ros/indigo/lib/x86_64-linux-gnu/pkgconfig:/home/nico/catkin_ws/ugv/devel/lib/pkgconfig:/home/nico/catkin_ws/test/devel/lib/pkgconfig:/home/nico/catkin_ws/robot_localization/devel/lib/pkgconfig:/home/nico/catkin_ws/tum_ardrone/devel/lib/pkgconfig:/home/nico/catkin_ws/laser_camera_calibration/devel/lib/pkgconfig:/opt/ros/indigo/lib/pkgconfig"
export PWD="/home/nico/Vision/SLAM/ORB_official/ORB_SLAM2/Examples/ROS/ORB_SLAM2/build-ORB_SLAM2-Desktop-Default"
export PYTHONPATH="/home/nico/Vision/SLAM/ORB_official/ORB_SLAM2/Examples/ROS/ORB_SLAM2/build-ORB_SLAM2-Desktop-Default/devel/lib/python2.7/dist-packages:$PYTHONPATH"
export ROSLISP_PACKAGE_DIRECTORIES="/home/nico/Vision/SLAM/ORB_official/ORB_SLAM2/Examples/ROS/ORB_SLAM2/build-ORB_SLAM2-Desktop-Default/devel/share/common-lisp:$ROSLISP_PACKAGE_DIRECTORIES"
export ROS_PACKAGE_PATH="/home/nico/Vision/SLAM/ORB_official/ORB_SLAM2/Examples/ROS/ORB_SLAM2:/home/nico/catkin_ws/ugv/src:/home/nico/catkin_ws/tum_ardrone/src:/opt/ros/indigo/share:/opt/ros/indigo/stacks"